---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EKSclusternameeks:
    Type: String
    Description: Enter the cluster name to be provisioned
  Version:
    Type: String
    Description: Enter the cluster version to be provisioned
  sgcontrolplaneeks:
    Type: String
    Description: Enter the security group name for cluster
  VpcIdeks:
    Description: The VPC of the worker instances
    Type: String
  SubnetIdeks:
    Description: Select 3 subnets where workers can be created
    Type: String
  SubnetIdsworker:
    Description: Select 3 subnets where workers can be created
    Type: String
  KeyNameworker:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: String
  NodeImageId:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: String
  InstanceTypeParameter:
    Type: String
    Description: EC2 instance type for the node instances
  NodeAutoScalingGroupMinSize:
    Description: Minimum size of Node Group ASG
    Type: Number
  NodeAutoScalingGroupMaxSize:
    Description: Maximum size of Node Group ASG. Set to at least 1 greater than NodeAutoScalingGroupDesiredCapacity.
    Type: Number
  NodeAutoScalingGroupDesiredCapacity:
    Description: Desired capacity of Node Group ASG.
    Type: Number
  NodeVolumeSize:
    Description: Node volume size
    Type: Number
  BootstrapArguments:
    Description: Arguments to pass to the bootstrap script. See files/bootstrap.sh
      in https://github.com/awslabs/amazon-eks-ami
    Type: String
  NodeGroupName:
    Description: Unique identifier for the Node Group.
    Type: String
  NodeGroupRoleName:
    Description: Unique identifier for the Node Group.
    Type: String
Resources:
  ChildStack01:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://132147-test-for-cft.s3.ap-south-1.amazonaws.com/eks-cluster-child-01.yaml
      Parameters:
        EKSclustername:
          Ref: EKSclusternameeks
        Version:
          Ref: Version
        sgcontrolplane:
          Ref: sgcontrolplaneeks
        VpcIdeks:
          Ref: VpcIdeks
        SubnetIdseks:
          Ref: SubnetIdeks
      TimeoutInMinutes: '1200'
  ChildStack02:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://132147-test-for-cft.s3.ap-south-1.amazonaws.com/eks-workernode-child-02.yaml
      Parameters:
        KeyName:
          Ref: KeyNameworker
        NodeImageId:
          Ref: NodeImageId
        NodeInstanceType:
          Ref: InstanceTypeParameter
        NodeAutoScalingGroupMinSize:
          Ref: NodeAutoScalingGroupMinSize
        NodeAutoScalingGroupMaxSize:
          Ref: NodeAutoScalingGroupMaxSize
        NodeAutoScalingGroupDesiredCapacity:
          Ref: NodeAutoScalingGroupDesiredCapacity
        NodeVolumeSize:
          Ref: NodeVolumeSize
        ClusterName:
          Ref: EKSclusternameeks
        BootstrapArguments:
          Ref: BootstrapArguments
        NodeGroupName:
          Ref: NodeGroupName
        NodeGroupRoleName:
          Ref: NodeGroupRoleName
        ClusterControlPlaneSecurityGroup:
          Fn::GetAtt:
          - ChildStack01
          - Outputs.clusterSecurityGroup
        VpcId:
          Ref: VpcIdeks
        Subnets:
          Ref: SubnetIdsworker
      TimeoutInMinutes: '300'
Outputs:
  NodeInstanceRole:
    Value:
      Fn::GetAtt:
      - ChildStack02
      - Outputs.NodeInstanceRole
  Kubernetesaccessrole:
    Value:
      Fn::GetAtt:
      - ChildStack01
      - Outputs.Kubernetesaccessrole
